### PR TITLE
number=1

### PR DESCRIPTION
**Pull request by aaronspring**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@aaronspring

Thanks!

I'm up for maintaining here, but I think you need to open an issue to add me as one: https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by aaronspring** [comment]
@Zeitsperre should I change more in the dependencies? CI passed but not sure whether thats the ultimate test already

**Comment by Zeitsperre** [comment]
I'm not sure if you really need to pin `esmpy =*=mpi*`? In fact, given that the `xesmf` package manages that dependency, unless mpi support is something very specifically needed, I'd remove that entry altogether.

**Comment by Zeitsperre** [comment]
Given that I now have access, I can perform these changes if you'd like!

**Review by Zeitsperre — APPROVED** [review]

**Comment by Zeitsperre** [comment]
@aaronspring

I'll release a build here with `esmpy` handled by `xesmf`. If this needs to be revisited, let me know!

**Pull request merged**
